### ISSUE TITLE
Event loop is closed after a test but new default event loop is not created

### ISSUE THREAD

**Issue by tmaila** [kwarunek/aiounittest#10]
When running multiple test cases using aiounittest under Python 3.8, the second and all the following unit test cases fail because there is no default event loop set in the MainThread. The following exception is raised when the unit tests are executed.

```bash
Traceback (most recent call last):
  File "lib\site-packages\aiounittest\helpers.py", line 130, in wrapper
    loop = get_brand_new_default_event_loop()
  File "lib\site-packages\aiounittest\helpers.py", line 117, in get_brand_new_default_event_loop
    old_loop = asyncio.get_event_loop()
  File "lib\asyncio\events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
```

This exception occurs because get_brand_new_default_event_loop tries to get the default event loop after it has been closed in the decorator.

**Comment by kwarunek** [comment]
Merged and published

**Comment by nardew** [comment]
Hello, I face the same issue even though using version 1.3.1. Could it be related to my Python version which is 3.7?
