### ISSUE TITLE
patch on method/class level

### ISSUE THREAD

**Issue by jorotenev** [kwarunek/aiounittest#15]
Hi :)
```python
class Test(AsyncTestCase):
    @patch('some_path.features_topic.send', new=AsyncMock())
    async def test_smoke(self, mocked_topic):
        ...
```
I get a `TypeError: test_smoke() missing 1 required positional argument: 'mocked_topic'`

If I patch within the test with a `with patch(..) as patched_object:` it works fine.

**Comment by kwarunek** [comment]
Please take a look at https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch. AFAICT you should use `new_callable` if used as decorator to get mocked object as a parameter.

``` python
class Test(AsyncTestCase):
    @patch('some_path.features_topic.send', new_callable=AsyncMock)
    async def test_smoke(self, mocked_topic):
```
