### ISSUE TITLE
Mock

### ISSUE THREAD

**Issue by Olegt0rr** [kwarunek/aiounittest#2]
Hi there!
What about unittest.mock in asyncio?

**Comment by kwarunek** [comment]
To be honest I left this issue due to lack of my understanding, sorry.  A mock object cooperates perfectly with a `futurized` and can be used to mock/patch coroutines. Additionally in the meantime I've added helper - to mock async iterators.

**Comment by dapicester** [comment]
I bumped into this today and I managed to get it working like this:
```py
class MyTest(unittest.TestCase):
  @mock('myfunction')
  @async_test
  async def test_myfunc(self, mock):
    mock.return_value = futurized(42)
    result = await myfunction()
    self.assertEqual(result, 42)
```

The key is to have the mock's `return_value` and/or `side_effect` to return `futurized` values.

When using the `async_test` decorator ensure that it is the closest decorator to the test function.

Hope this helps.
