### ISSUE TITLE
setUp and tearDown can't be async

### ISSUE THREAD

**Issue by jcmcken** [kwarunek/aiounittest#4]
The ``AsyncTestCase`` assumes that only methods named ``test_*`` can be async, which isn't necessarily a valid assumption. This restriction should be removed, since you already test if the given function is a coroutine.

**Comment by kwarunek** [comment]
Async setUp/tearDown approach would make a bit complicated - cop/mock more with the unittest's internals. In the Python 3.8 and newer consider to use the unittest.IsolatedAsyncioTestCase. Builtin unittest module is now asyncio-featured and it's happened to have requested feature..
