### ISSUE TITLE
Latest version isn't published to PyPI

### ISSUE THREAD

**Issue by jcmcken** [kwarunek/aiounittest#5]
The PyPI version does not check if a test case method is a coroutine, only that it is a callable. This differs from what's in this repo, which I think is the more correct behavior:

```python
    def __getattribute__(self, name):
        attr = super().__getattribute__(name)
        if name.startswith('test_') and callable(attr):
            return async_test(attr, loop=self.get_event_loop())
        else:
            return attr
```

**Comment by kwarunek** [comment]
hmm, that's odd, thanks I've published it with new feature.
